# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Geolocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, lat: float=None, lon: float=None, timestamp: datetime=None):  # noqa: E501
        """Geolocation - a model defined in Swagger

        :param lat: The lat of this Geolocation.  # noqa: E501
        :type lat: float
        :param lon: The lon of this Geolocation.  # noqa: E501
        :type lon: float
        :param timestamp: The timestamp of this Geolocation.  # noqa: E501
        :type timestamp: datetime
        """
        self.swagger_types = {
            'lat': float,
            'lon': float,
            'timestamp': datetime
        }

        self.attribute_map = {
            'lat': 'lat',
            'lon': 'lon',
            'timestamp': 'timestamp'
        }

        self._lat = lat
        self._lon = lon
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'Geolocation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Geolocation of this Geolocation.  # noqa: E501
        :rtype: Geolocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self) -> float:
        """Gets the lat of this Geolocation.


        :return: The lat of this Geolocation.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat: float):
        """Sets the lat of this Geolocation.


        :param lat: The lat of this Geolocation.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self) -> float:
        """Gets the lon of this Geolocation.


        :return: The lon of this Geolocation.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon: float):
        """Sets the lon of this Geolocation.


        :param lon: The lon of this Geolocation.
        :type lon: float
        """

        self._lon = lon

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this Geolocation.


        :return: The timestamp of this Geolocation.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this Geolocation.


        :param timestamp: The timestamp of this Geolocation.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
