# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from db_micro.models.base_model_ import Model
from db_micro import util


class ServerError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error_code: int=None, message: str=None):  # noqa: E501
        """ServerError - a model defined in Swagger

        :param error_code: The error_code of this ServerError.  # noqa: E501
        :type error_code: int
        :param message: The message of this ServerError.  # noqa: E501
        :type message: str
        """
        self.swagger_types = {
            'error_code': int,
            'message': str
        }

        self.attribute_map = {
            'error_code': 'errorCode',
            'message': 'message'
        }

        self._error_code = error_code
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'ServerError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServerError of this ServerError.  # noqa: E501
        :rtype: ServerError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_code(self) -> int:
        """Gets the error_code of this ServerError.


        :return: The error_code of this ServerError.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this ServerError.


        :param error_code: The error_code of this ServerError.
        :type error_code: int
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def message(self) -> str:
        """Gets the message of this ServerError.


        :return: The message of this ServerError.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ServerError.


        :param message: The message of this ServerError.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
